module.exports = {
  areas: {
    cult: {
      url: "/kb/culture-overview",
      label: "Culture",
      color: "bg-red-400",
      emoji_code: "performing_arts",
      categories: {
        ov: { label: "Overview" },
        arts: { label: "Performing Arts" },
        vis: { label: "Visual Arts" },
        media: { label: "Mass Media" },
        food: { label: "Food & Drink" },
        lit: { label: "Literature" },
      },
    },
    math: {
      label: "Mathematics",
      url: "/kb/mathematics-overview",
      color: "bg-green-500",
      emoji_code: "1234",
      categories: {
        ov: { label: "Overview" },
        res: { label: "Research" },
        ml: { label: "ML & Stats" },
        cs: { label: "Computer science" },
        cv: { label: "Computer vision" },
        rl: { label: "Reinforcement learning" },
        la: { label: "Linear Algebra" },
        uncat: { label: "Uncategorized" },
      },
    },
    meta: {
      label: "Meta",
      url: "/kb/meta-overview",
      color: "bg-blue-500",
      emoji_code: "bulb",
      categories: {
        ov: { label: "Overview" },
        info: { label: "Info" },
        sys: { label: "System" },
      },
    },
    nat: {
      label: "Natural sciences",
      url: "/kb/natural-sciences-overview",
      color: "bg-green-600",
      emoji_code: "leaves",
      categories: {
        ov: { label: "Overview" },
        ph: { label: "Physics" },
        neur: { label: "Neuroscience" },
        geo: { label: "Earth sciences" },
        bio: { label: "Biology" },
      },
    },
    people: {
      label: "People",
      url: "/kb/people-overview",
      color: "bg-red-600",
      emoji_code: "information_desk_person",
      categories: {
        ov: { label: "Overview" },
        th: { label: "Thoughts" },
        anth: { label: "Anthropology" },
        bio: { label: "Biographies" },
        uncat: { label: "Uncategorized" },
      },
    },
    phil: {
      label: "Philosophy",
      url: "/kb/philosophy-overview",
      color: "bg-pink-400",
      emoji_code: "thought_balloon",
      categories: {
        ov: { label: "Overview" },
        term: { label: "Terms" },
        psych: { label: "Cognitive psychology" },
        meta: { label: "Metaphysics" },
        mm: { label: "Mental Models" },
        uncat: { label: "Uncategorized" },
      },
    },
    ref: {
      label: "Reference",
      url: "/kb/reference-overview",
      color: "bg-blue-600",
      emoji_code: "books",
      categories: {
        ov: { label: "Overview" },
        books: { label: "Books" },
        www: { label: "WWW" },
        hb: { label: "Handbook" },
        data: { label: "Data & Viz." },
      },
    },
    soc: {
      label: "Society",
      url: "/kb/society-overview",
      color: "bg-pink-700",
      emoji_code: "classical_building",
      categories: {
        ov: { label: "Overview" },
        biz: { label: "Business" },
        econ: { label: "Economics" },
        edu: { label: "Education" },
        gov: { label: "Government" },
        jrn: { label: "Journalism" },
        org: { label: "Orgs. and Institutions" },
        ssc: { label: "Social sciences" },
        uncat: { label: "Uncategorized" },
      },
    },
    tech: {
      label: "Technology",
      url: "/kb/technology-overview",
      color: "bg-yellow-500",
      emoji_code: "rocket",
      categories: {
        ov: { label: "Overview" },
        ideas: { label: "Ideas" },
        prod: { label: "Products" },
        swe: { label: "Software Eng." },
        uncat: { label: "Uncategorized" },
      },
    },
  },
}
